name: Assignment 3 Unit Tests

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive
    
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential cmake gcc g++
    
    - name: Create build directory
      run: mkdir -p build
    
    - name: Configure CMake
      run: cd build && cmake ..
    
    - name: Build project
      run: cd build && make
    
    - name: Run unit tests
      run: ./unit-test.sh
    
    - name: Run full test suite
      run: ./full-test.sh