name: Assignment Tests

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    container: cuaesd/aesd-autotest:unit-test
    runs-on: self-hosted
    
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive
    
    - name: Clean build directory
      run: rm -rf build
    
    - name: Run unit tests
      run: ./unit-test.sh
    
    - name: Run full test suite
      run: ./full-test.sh